gitlab:
  token: "token"
  webhook_method: "webhook"
  webhook_port: 80
  actions:
    - "open"
    - "reopen"
    - "update"
    - "close"
telegram:
  token: "token"
  chat_id: 1
  workers_count: 2
  debug: true
users:
  - "user1"
  - "user2"
projects:
  - "project1"
  - "project2"